

---
title: "visNetwork"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(visNetwork)
```

## R MarkdownPackage ‘visNetwork"
December 5, 2018
Title Network Visualization using 'vis.js' Library
Version 2.0.5
Date 2018-12-05
Maintainer Benoit Thieurmel <benoit.thieurmel@datastorm.fr>
Description Provides an R interface to the 'vis.js' JavaScript charting
library. It allows an interactive visualization of networks.
BugReports https://github.com/datastorm-open/visNetwork/issues
URL http://datastorm-open.github.io/visNetwork/
Depends R (>= 3.0)
Imports htmlwidgets, htmltools, jsonlite, magrittr, utils, methods,
grDevices, stats
License MIT + file LICENSE
Suggests knitr, rmarkdown, webshot, igraph, rpart, shiny,
shinyWidgets, colourpicker, sparkline, ggraph, flashClust
VignetteBuilder knitr, rmarkdown, webshot
RoxygenNote 6.0.1
NeedsCompilation no
Author Almende B.V. [aut, cph] (vis.js library in htmlwidgets/lib,
http://visjs.org, http://www.almende.com/home),
Benoit Thieurmel [aut, cre] (R interface),
Titouan Robert [aut, ctb]
Repository CRAN
Date/Publication 2018-12-05 08:40:03 UTC
R topics documented:
addExport..... . . 3
addFontAwesome.... . . . . . . 4
addIonicons..... . 5
visClusteringByColor.... . . . . 5
1
2 R topics documented:
visClusteringByConnection.... . 6
visClusteringByGroup.... . . . 7
visClusteringByHubsize.... . . 8
visClusteringOutliers.... . . . . 9
visConfigure..... . 9
visDocumentation.... . . . . . . 11
visEdges..... . . . 11
visEvents..... . . 16
visExport..... . . 20
visFit..... . . . . 21
visFocus..... . . . 22
visGetBoundingBox.... . . . . 23
visGetConnectedEdges.... . . . 24
visGetConnectedNodes.... . . . 25
visGetEdges..... . 26
visGetNodes..... . 27
visGetPositions....28
visGetScale..... . 29
visGetSelectedEdges.... . . . . 30
visGetSelectedNodes.... . . . . 31
visGetSelection....32
visGetViewPosition.... . . . . . 33
visGroups..... . . 34
visHclust..... . . 35
visHierarchicalLayout.... . . . . 37
visIgraphLayout....39
visInteraction..... 41
visLayout..... . . 44
visLegend..... . . 45
visMoveNode..... 47
visNearestNodes.... . . . . . . 48
visNetwork..... . 49
visNetwork-collapse.... . . . . 53
visNetwork-igraph.... . . . . . 55
visNetwork-shiny.... . . . . . . 57
visNetwork-treeModule.... . . . 58
visNetworkEditor.... . . . . . . 61
visNetworkEditor-module.... . 62
visNodes..... . . 64
visOptions..... . . 68
visPhysics..... . . 73
visRedraw..... . . 77
visRemoveEdges.... . . . . . . 78
visRemoveNodes.... . . . . . . 79
visSave..... . . . 80
visSelectEdges....81
visSelectNodes....82
visSetData..... . . 83
addExport 3
visSetOptions..... 84
visSetSelection....85
visSetTitle..... . . 86
visStabilize..... . 87
visStartSimulation.... . . . . . . 88
visStopSimulation.... . . . . . . 88
visStorePositions.... . . . . . . 89
visTree..... . . . 90
visTreeEditor..... 93
visUnselectAll..... 94
visUpdateEdges....95
visUpdateNodes....96
%>%..... . . . . 97
Index 98
