
visGetPositions Network visualization getPositions method

#### Description
For use getPositions() method in a shiny app. For full documentation, have a look at visDocumentation.

#### Usage
<pre><code>
visGetPositions(graph, nodes = NULL, input = paste0(graph$id, "_positions"))
</code></pre>

#### Arguments
* ``graph`` : a visNetworkProxy object nodes : NULL for all nodes (Default), or a vector of nodes id
* ``input`` : name of shiny input created. Default to paste0(graph$id, "_positions")

#### Examples
```{r}

shiny::runApp(system.file("shiny", package = "visNetwork"))

```

#### References
See online documentation http://datastorm-open.github.io/visNetwork/
See Also
visNodes for nodes options, visEdges for edges options, visGroups for groups options, visLegend
for adding legend, visOptions for custom option, visLayout & visHierarchicalLayout for layout,
visPhysics for control physics, visInteraction for interaction, visNetworkProxy & visFocus & visFit
for animation within shiny, visDocumentation, visEvents, visConfigure ...
