visGetConnectedNodes 25
visGetConnectedNodes Method getConnectedNodes, with shiny only.
#### Description
Method getConnectedNodes, with shiny only. Returns a vector of nodeIds of the all the nodes that
are directly connected to this node. If you supply an edgeId, vis will first match the id to nodes.
#### Usage
<pre><code>
visGetConnectedNodes(graph, id, input = paste0(graph$id, "_connectedNodes"))
</code></pre>
#### Arguments
* ``graph`` : a visNetworkProxy object
id : a node or edge id
* ``input`` : name of shiny input created. Default to paste0(graph$id, "_connectedNodes")
#### References
See online documentation http://datastorm-open.github.io/visNetwork/
See Also
visNodes for nodes options, visEdges for edges options, visGroups for groups options, visLegend
for adding legend, visOptions for custom option, visLayout & visHierarchicalLayout for layout,
visPhysics for control physics, visInteraction for interaction, visNetworkProxy & visFocus & visFit
for animation within shiny, visDocumentation, visEvents, visConfigure ...
#### Examples
```{r}
## Not run:
# have a look to :
shiny::runApp(system.file("shiny", package = "visNetwork"))
## End(Not run)
```
