
visRemoveNodes Function to remove nodes from network, with shiny only.
#### Description
Function to remove nodes from network, with shiny only.
#### Usage
<pre><code>
visRemoveNodes(graph, id, updateOptions = TRUE, legend = FALSE)
</code></pre>
#### Arguments
* ``graph`` : a visNetworkProxy object
* ``id`` : vector of id, nodes to remove
* ``updateOptions`` : Boolean. Update options (nodesIdSelection & selectedBy) if needed ? Default to TRUE.
* ``legend`` :   Boolean. Remove nodes on legend ? Default to FALSE

#### Examples
```{r}
## Not run:
# have a look to :
shiny::runApp(system.file("shiny", package = "visNetwork"))
## End(Not run)
```

#### References
See online documentation http://datastorm-open.github.io/visNetwork/
See Also
visNodes for nodes options, visEdges for edges options, visGroups for groups options, visLegend
for adding legend, visOptions for custom option, visLayout & visHierarchicalLayout for layout,
visPhysics for control physics, visInteraction for interaction, visNetworkProxy & visFocus & visFit
for animation within shiny, visDocumentation, visEvents, visConfigure ...
